apiVersion: v1
kind: Namespace
metadata:
  name: virtualserver-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtualserver-app
  namespace: virtualserver-app
  labels:
    app: virtualserver-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtualserver-app
  template:
    metadata:
      labels:
        app: virtualserver-app
    spec:
      containers:
      - name: virtualserver-app
        image: jgoodier/nginx-hello:plaintext
        ports:
          - containerPort: 80
            protocol: TCP
        resources: {}
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: virtualserver-app
  namespace: virtualserver-app
spec:
  ports:
    - name: virtualserver-app
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: virtualserver-app
  type: ClusterIP
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: virtualserver-app
  namespace: virtualserver-app
spec:
  # which ingress controller to use
  ingressClassName: nginx2
  host: vs.nginx2.nginx.rocks
  # tls:
  #   secret: cafe-secret
  upstreams:
  - name: tea
    service: virtualserver-app
    port: 80
  routes:
  - path: /tea
    action:
      pass: tea