
apiVersion: v1
kind: Namespace
metadata:
  name: virtualserverroute-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtualserverroute-app
  namespace: virtualserverroute-app
  labels:
    app: virtualserverroute-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtualserverroute-app
  template:
    metadata:
      labels:
        app: virtualserverroute-app
    spec:
      containers:
      - name: virtualserverroute-app
        image: jgoodier/nginx-hello:plaintext
        ports:
          - containerPort: 80
            protocol: TCP
        resources: {}
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: virtualserverroute-app
  namespace: virtualserverroute-app
spec:
  ports:
    - name: virtualserverroute-app
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: virtualserverroute-app
  type: ClusterIP
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: virtualserver-app
  namespace: virtualserver-app
spec:
  ingressClassName: nginx3
  host: vs.nginx3.nginx.rocks
  # tls:
  #   secret: cafe-secret
  upstreams:
  - name: items
    service: virtualserver-app
    port: 80
  routes:
  - path: /items
    action:
      pass: items
---      
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: virtualserverroute-app
  namespace: virtualserverroute-app
spec:
  ingressClassName: nginx3
  host: vs.nginx3.nginx.rocks
  # tls:
  #   secret: cafe-secret
  upstreams:
  - name: tea
    service: virtualserverroute-app
    port: 80
  - name: beer
    service: virtualserverroute-app
    port: 80
  subroutes:
  - path: /items/tea
    action:
      pass: tea
  - path: /items/beer
    action:
      pass: beer