apiVersion: v1
kind: Namespace
metadata:
  name: virtualserver-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtualserver-app
  namespace: virtualserver-app
  labels:
    app: virtualserver-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtualserver-app
  template:
    metadata:
      labels:
        app: virtualserver-app
    spec:
      containers:
      - name: virtualserver-app
        image: nginxinc/nginx-unprivileged
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: "100Mi"
          requests:
            cpu: "0.1"
            memory: "20Mi"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: default-conf
          readOnly: true
      volumes:
      - name: default-conf
        configMap:
          name: nginx-echo
          items:
            - key: default.conf
              path: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: virtualserver-app
  namespace: virtualserver-app
spec:
  ports:
    - name: virtualserver-app
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: virtualserver-app
  type: ClusterIP
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: virtualserver-app
  namespace: virtualserver-app
spec:
  ingressClassName: nginx
  host: "hello-vs.k8s.nginx.rocks"
  routes:
  - path: /
    action:
      pass: virtualserver-app-upstream
  upstreams:
    - name: virtualserver-app-upstream
      service: virtualserver-app
      port: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-echo
  namespace: virtualserver-app
data:
  default.conf: |
    server {
        listen 8080;
        location / {
            default_type text/plain;
            expires -1;
            return 200 'Server address: $server_addr:$server_port\nServer name: $hostname\nDate: $time_local\nURI: $request_uri\nRequest ID: $request_id\nHost header: $Host\n';
        }
    }