prometheus:
  create: true
  scheme: http
  port: 9113
controller:
  nginxplus: true
  # hostNetwork: true
  image:
    repository: private-registry.nginx.com/nginx-ic-nap/nginx-plus-ingress
    tag: 2.0.3-ubi
  serviceAccount:
    # name: nginx-ingress
    imagePullSecretName: regcred
  setAsDefaultIngress: true
  ingressClass: nginx
  enableCustomResources: true
  enablePreviewPolicies: true
  enableTLSPassthrough: true  
  appprotect:
    enable: true
  enableSnippets: true
  healthStatus: true
  latency-metrics: true
  nginxStatus:
    ## Enable the NGINX stub_status, or the NGINX Plus API.
    enable: true
    port: 8080
    ## Add IPv4 IP/CIDR blocks to the allow list for the NGINX Plus API. Separate multiple IP/CIDR by commas.
    allowCidrs: "0.0.0.0/0"
  globalConfiguration:
    create: true
    spec:
      listeners:
        - name: redis-tcp
          port: 6379
          protocol: TCP
  service:
    extraLabels:
      # needs to match ServiceMonitor matchLabels
      app: nginx-ingress-controller
    customPorts:
    - name: dashboard
      targetPort: 8080
      protocol: TCP
      port: 8080
    - name: prometheus
      targetPort: 9113
      protocol: TCP
      port: 9113
    - name: redis-tcp
      targetPort: 6379
      protocol: TCP
      port: 6379
  config:
    entries:
      http2: "true"
      # smarter LB method:
      lb-method: "least_time last_byte"
      # for debugging
      error-log-level: info
      # plus level logging:
      #log-format:  '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" rn="$resource_name" "$resource_type" "$resource_namespace" svc="$service" "$request_id" rt=“$request_time” ua=“$upstream_addr” uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time" uqt=“$upstream_queue_time“ cs=“$upstream_cache_status“'
      log-format: |-
        json
          {
            \"ancient_browser\":\"$ancient_browser\",
            \"arg_\":\"$arg_\",
            \"args\":\"$args\",
            \"body_bytes_sent\":\"$body_bytes_sent\",
            \"bytes_sent\":\"$bytes_sent\",
            \"connection\":\"$connection\",
            \"connection_requests\":\"$connection_requests\",
            \"connections_active\":\"$connections_active\",
            \"connections_reading\":\"$connections_reading\",
            \"connections_writing\":\"$connections_writing\",
            \"content_length\":\"$content_length\",
            \"content_type\":\"$content_type\",
            \"cookie_\":\"$cookie_\",
            \"date_gmt\":\"$date_gmt\",
            \"date_local\":\"$date_local\",
            \"document_root\":\"$document_root\",
            \"document_uri\":\"$document_uri\",
            \"fastcgi_path_info\":\"$fastcgi_path_info\",
            \"fastcgi_script_name\":\"$fastcgi_script_name\",
            \"gzip_ratio\":\"$gzip_ratio\",
            \"host\":\"$host\",
            \"hostname\":\"$hostname\",
            \"http2\":\"$http2\",
            \"http_\":\"$http_\",
            \"https\":\"$https\",
            \"invalid_referer\":\"$invalid_referer\",
            \"is_args\":\"$is_args\",
            \"jwt_claim_\":\"$jwt_claim_\",
            \"jwt_header_\":\"$jwt_header_\",
            \"limit_conn_status\":\"$limit_conn_status\",
            \"limit_rate\":\"$limit_rate\",
            \"limit_req_status\":\"$limit_req_status\",
            \"modern_browser\":\"$modern_browser\",
            \"msec\":\"$msec\",\"msie\":\"$msie\",
            \"nginx_version\":\"$nginx_version\",
            \"pid\":\"$pid\",
            \"pipe\":\"$pipe\",
            \"proxy_add_x_forwarded_for\":\"$proxy_add_x_forwarded_for\",
            \"proxy_host\":\"$proxy_host\",
            \"proxy_port\":\"$proxy_port\",
            \"proxy_protocol_addr\":\"$proxy_protocol_addr\",
            \"proxy_protocol_port\":\"$proxy_protocol_port\",
            \"proxy_protocol_server_addr\":\"$proxy_protocol_server_addr\",
            \"proxy_protocol_server_port\":\"$proxy_protocol_server_port\",
            \"query_string\":\"$query_string\",
            \"realip_remote_addr\":\"$realip_remote_addr\",
            \"realip_remote_port\":\"$realip_remote_port\",
            \"realpath_root\":\"$realpath_root\",
            \"remote_addr\":\"$remote_addr\",
            \"remote_port\":\"$remote_port\",
            \"remote_user\":\"$remote_user\",
            \"request\":\"$request\",
            \"request_body\":\"$request_body\",
            \"request_body_file\":\"$request_body_file\",
            \"request_completion\":\"$request_completion\",
            \"request_filename\":\"$request_filename\",
            \"request_id\":\"$request_id\",
            \"request_length\":\"$request_length\",
            \"request_method\":\"$request_method\",
            \"request_time\":\"$request_time\",
            \"request_uri\":\"$request_uri\",
            \"scheme\":\"$scheme\",
            \"secure_link\":\"$secure_link\",
            \"secure_link_expires\":\"$secure_link_expires\",
            \"sent_http_\":\"$sent_http_\",
            \"sent_trailer_\":\"$sent_trailer_\",
            \"server_addr\":\"$server_addr\",
            \"server_name\":\"$server_name\",
            \"server_port\":\"$server_port\",
            \"server_protocol\":\"$server_protocol\",
            \"session_log_binary_id\":\"$session_log_binary_id\",
            \"session_log_id\":\"$session_log_id\",
            \"slice_range\":\"$slice_range\",
            \"ssl_cipher\":\"$ssl_cipher\",
            \"ssl_ciphers\":\"$ssl_ciphers\",
            \"ssl_client_cert\":\"$ssl_client_cert\",
            \"ssl_client_escaped_cert\":\"$ssl_client_escaped_cert\",
            \"ssl_client_fingerprint\":\"$ssl_client_fingerprint\",
            \"ssl_client_i_dn\":\"$ssl_client_i_dn\",
            \"ssl_client_i_dn_legacy\":\"$ssl_client_i_dn_legacy\",
            \"ssl_client_raw_cert\":\"$ssl_client_raw_cert\",
            \"ssl_client_s_dn\":\"$ssl_client_s_dn\",
            \"ssl_client_s_dn_legacy\":\"$ssl_client_s_dn_legacy\",
            \"ssl_client_serial\":\"$ssl_client_serial\",
            \"ssl_client_v_end\":\"$ssl_client_v_end\",
            \"ssl_client_v_remain\":\"$ssl_client_v_remain\",
            \"ssl_client_v_start\":\"$ssl_client_v_start\",
            \"ssl_client_verify\":\"$ssl_client_verify\",
            \"ssl_curves\":\"$ssl_curves\",
            \"ssl_early_data\":\"$ssl_early_data\",
            \"ssl_protocol\":\"$ssl_protocol\",
            \"ssl_server_name\":\"$ssl_server_name\",
            \"ssl_session_id\":\"$ssl_session_id\",
            \"ssl_session_reused\":\"$ssl_session_reused\",
            \"status\":\"$status\",
            \"tcpinfo_rtt\":\"$tcpinfo_rtt\",
            \"tcpinfo_rttvar\":\"$tcpinfo_rttvar\",
            \"tcpinfo_snd_cwnd\":\"$tcpinfo_snd_cwnd\",
            \"tcpinfo_rcv_space\":\"$tcpinfo_rcv_space\",
            \"time_iso8601\":\"$time_iso8601\",
            \"time_local\":\"$time_local\",
            \"uid_got\":\"$uid_got\",
            \"uid_reset\":\"$uid_reset\",
            \"uid_set\":\"$uid_set\",
            \"upstream_addr\":\"$upstream_addr\",
            \"upstream_bytes_received\":\"$upstream_bytes_received\",
            \"upstream_bytes_sent\":\"$upstream_bytes_sent\",
            \"upstream_cache_status\":\"$upstream_cache_status\",
            \"upstream_connect_time\":\"$upstream_connect_time\",
            \"upstream_cookie_\":\"$upstream_cookie_\",
            \"upstream_header_time\":\"$upstream_header_time\",
            \"upstream_http_\":\"$upstream_http_\",
            \"upstream_queue_time\":\"$upstream_queue_time\",
            \"upstream_response_length\":\"$upstream_response_length\",
            \"upstream_response_time\":\"$upstream_response_time\",
            \"upstream_status\":\"$upstream_status\",
            \"upstream_trailer_\":\"$upstream_trailer_\",
            \"uri\":\"$uri\"
          };
